[package]
name = "part1"
version = "0.1.0"
authors = ["Rubén Durán Balda <ruduran@users.noreply.github.com>"]

[dependencies]

[lib]
name = "day01"
path = "src/day01.rs"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
